Github Actions deploy to Container Registry at Heroku
Pro100Team/accman-be pull request #11
Opened 2022-07-18 15:44 UTC by lmiadowicz

Overview: Allow automatic maven + docker container builds be deployed to Heroku via Github Actions
* added ./finance_manager/docker/Dockerfile_prod
* added .github/workflow/accman-be-deploy-action.yml
* added Heroku secrets in Github's account Settings/Secrets/Actions

2022-07-19 20:39 UTC, SokilV requested changes

2022-07-19 21:50 UTC, lmiadowicz commented on .github/workflows/accman-be-deploy-action.yml
> +name: Java CI with Maven & Heroku
This is not good practice to run postgres in docker container on production you or sb even said it during the lecture. 
I read about it before too (https://vsupalov.com/database-in-docker/) this is why I connected this container to managed Heroku db and this is industry standard on every cloud provider....Don't understand rationale here, sorry.

2022-07-19 21:56 UTC, lmiadowicz commented on .github/workflows/accman-be-deploy-action.yml
> +  push:
I tested this on my private repo it works when you merge pull request if you check the [documentation](https://docs.github.com/en/enterprise-server@3.3/actions/using-workflows/events-that-trigger-workflows#create) you will not find any merge event. I'm testing everything before I create commit this is why I did private repo to be 100% sure before I introduce sth to the workflow you defined at the beginning.

2022-07-21 10:57 UTC, SokilV commented on .github/workflows/accman-be-deploy-action.yml
> +name: Java CI with Maven & Heroku
The application is a test application, not production.
DB in docker is a good solution for testing and development anyway.
The main idea is to run the environment fast.

2022-07-21 10:58 UTC, SokilV approved these changes

2022-07-21 10:58 UTC, merged